import { Volkhov } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-volkhov",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="en" >
      <body className={volkhov.variable}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
